name: Build and Deploy pumpkin-fe to Docker Hub and update tag in infra repo

on:
  push:
    branches: [ "main" ]
    paths:
      - "fe/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "fe/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./fe
          file: ./fe/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pumpkin-fe:${{ github.sha }}

      - name: Clone pumpkin_infra repo
        run: |
          git clone https://${{ secrets.PAT }}@github.com/elvish-ishaan/pumpkin_infra.git
          cd pumpkin_infra/helm/fe

          echo "inside prod directory"
          # Update image tag in values.yaml
          sed -i "s|tag: .*|tag: \"${{ github.sha }}\"|g" values.yaml

          echo "updated the image tag"

          # Commit and push changes
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update pumpkin-fe image to ${{ github.sha }}"
          git push
